
import { Flight, FlightStatus } from './types';

export const INITIAL_FLIGHTS: Flight[] = [
  {
    id: '1',
    flightNumber: 'AI203',
    source: 'New Delhi',
    destination: 'New York',
    departureTime: '10:30',
    terminal: 'T3',
    gate: '15A',
    status: FlightStatus.OnTime,
  },
  {
    id: '2',
    flightNumber: '6E502',
    source: 'Mumbai',
    destination: 'Dubai',
    departureTime: '11:00',
    terminal: 'T2',
    gate: '04B',
    status: FlightStatus.Boarding,
  },
  {
    id: '3',
    flightNumber: 'BA142',
    source: 'London',
    destination: 'Bangalore',
    departureTime: '12:15',
    terminal: 'T5',
    gate: 'C61',
    status: FlightStatus.Delayed,
  },
  {
    id: '4',
    flightNumber: 'EK517',
    source: 'Dubai',
    destination: 'New Delhi',
    departureTime: '13:00',
    terminal: 'T3',
    gate: '22C',
    status: FlightStatus.OnTime,
  },
    {
    id: '5',
    flightNumber: 'SQ401',
    source: 'Singapore',
    destination: 'Mumbai',
    departureTime: '14:45',
    terminal: 'T2',
    gate: 'E7',
    status: FlightStatus.Departed,
  },
  {
    id: '6',
    flightNumber: 'LH760',
    source: 'Frankfurt',
    destination: 'Delhi',
    departureTime: '15:20',
    terminal: 'T3',
    gate: '18A',
    status: FlightStatus.Cancelled,
  },
];
